name: ProtoWeaver
version: 'debug-build'
main: me.mrnavastar.protoweaver.paper.Paper
api-version: '1.13'

libraries:
  - io.netty:netty-codec-http:4.1.97.Final
  - io.netty:netty-codec-http2:4.1.97.Final
  - org.bouncycastle:bcpkix-jdk18on:1.77