name: ProtoWeaver
author: MrNavaStar
version: 'debug-build'
main: me.mrnavastar.protoweaver.loader.Paper
api-version: '1.13'
load: STARTUP
libraries:
  - org.apache.fury:fury-core:0.7.1
  - io.netty:netty-codec-http:4.1.97.Final
  - io.netty:netty-codec-http2:4.1.97.Final
  - org.bouncycastle:bcpkix-jdk18on:1.78.1
  - me.mrnavastar:r:1.0.8